# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:14
from __future__ import unicode_literals

import application.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_index=True, max_length=225)),
                ('brojponavljanja', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contentss',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(blank=True, null=True, storage=application.storage.OverwriteStorage(), upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='ipcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=225)),
                ('content', models.CharField(max_length=225)),
                ('counts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Najaktivniji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=225)),
                ('brojponavljanja', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'clineti',
                'verbose_name_plural': 'ipclienti',
            },
        ),
        migrations.CreateModel(
            name='nginxLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=225)),
                ('vrijeme', models.DateTimeField()),
                ('request', models.CharField(max_length=225)),
                ('status', models.BigIntegerField()),
                ('bandwidth', models.BigIntegerField()),
                ('user_agent', models.CharField(max_length=225)),
                ('referrer', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promet', models.CharField(max_length=225, null=True)),
                ('code200', models.IntegerField(null=True)),
                ('code404', models.IntegerField(null=True)),
                ('ip', models.IntegerField(null=True)),
                ('content', models.IntegerField(null=True)),
                ('fajl', models.CharField(max_length=225, null=True)),
                ('code', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('metod', models.IntegerField(null=True)),
                ('status400', models.IntegerField(null=True)),
                ('status403', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests_vrijeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme', models.DateTimeField(db_index=True)),
                ('requests', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requestmin',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BigIntegerField(db_index=True)),
                ('brojponavljanja', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour206',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour301',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour302',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour403',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour404',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour405',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour406',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_per_hour504',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('y', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='vrijeme_promet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme', models.DateTimeField(db_index=True)),
                ('promet', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=30, null=True)),
            ],
            options={
                'verbose_name': 'Promet',
                'verbose_name_plural': 'Prometmin',
            },
        ),
    ]
