# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20170227_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regex',
            name='regex',
            field=models.CharField(db_index=True, max_length=325, null=True),
        ),
    ]
