# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20170227_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall',
            name='userdefineminimalrequest',
            field=models.IntegerField(null=True),
        ),
    ]
