# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_overall_userdefineminimalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall',
            name='userdefineminimalrequest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
